[build]
  # Directory to change to before starting a build
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"
  
  # Default build command
  command = "pnpm run build"

[build.environment]
  # Node.js version
  NODE_VERSION = "22.20.0"
  
  # Enable pnpm
  NPM_FLAGS = "--version"
  
  # Disable telemetry
  NEXT_TELEMETRY_DISABLED = "1"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions (if needed in the future)
[functions]
  directory = "netlify/functions"
